spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/woman-shirt}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  jpa:
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT-SQL:true}
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ${SPRING_MAIL_USERNAME:hungnnit98@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:hzoyobgtgndaumvl}
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          starttls:
            enable:true
          auth: true

logging:
  level:
    org:
      hibernate: ERROR
server:
  error:
    include-message: always
cloud:
  name: ${CLOUD_NAME:hungnn22cloudinary}
  api:
    key: ${CLOUD_API_KEY:384426152519968}
    secret: ${CLOUD_API_SECRET:WjFBrrrKlAs1vU42mePi4FJLPW0}